[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"
    Content-Encoding = "gzip"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build]
publish = "dist"
command = "yarn build"

[build.environment]
NODE_VERSION = "20"
